name: deploy main
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!**-hotfix'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_NkovhVVGbIbF5AajdoHuc86w6lOC/l8XwTFrHgA