on:
  pull_request:
    types:
      - closed
    labeled: 
      - hotfix

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Config 
        run: |
          git config --global user.email "eng@artblocks.io" && git config --global user.name "artblocks eng"
      - name: create hotfix
        run: |
          git checkout -b hotfix $(git describe --tags $(git rev-list --tags --max-count=1)) && git cherry-pick ${{ github.sha }} && git push origin hotfix