on:
  pull_request:
    types:
      - closed
    labeled: 
      - hotfix

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Config 
        run: |
          git config --global user.email "eng@artblocks.io" && git config --global user.name "artblocks eng"
      - name: get tags
        run: | 
          git fetch --tags
      - name: create hotfix branch
        run: |
          git checkout -b hotfix $(git describe --tags $(git rev-list --tags --max-count=1))
      - name: cherry pick branch and push
        run: |
          git cherry-pick ${{ github.event.pull_request.head.sha }} --strategy-option=theirs
      - name: push
        run: |
          git push origin hotfix